// Theme reducer

export const SWITCH_THEME = "SWITCH_THEME";

// User reducer

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const CURRENT_USER_DATA_FETCH_REQUEST = "CURRENT_USER_DATA_FETCH_REQUEST";
export const CURRENT_USER_DATA_FETCH_SUCCESS = "CURRENT_USER_DATA_FETCH_SUCCESS";
export const CURRENT_USER_DATA_FETCH_FAILURE = "CURRENT_USER_DATA_FETCH_FAILURE";


// Recommendations reducer

export const RECOMMENDATIONS_FETCH_REQUEST = "RECOMMENDATIONS_FETCH_REQUEST";
export const RECOMMENDATIONS_FETCH_SUCCESS = "RECOMMENDATIONS_FETCH_SUCCESS";
export const RECOMMENDATIONS_FETCH_FAILURE = "RECOMMENDATIONS_FETCH_FAILURE";

// Recommendation details reducer

export const RECOMMENDATION_DETAILS_FETCH_REQUEST = "RECOMMENDATION_DETAILS_FETCH_REQUEST";
export const RECOMMENDATION_DETAILS_FETCH_SUCCESS = "RECOMMENDATION_DETAILS_FETCH_SUCCESS";
export const RECOMMENDATION_DETAILS_FETCH_FAILURE = "RECOMMENDATION_DETAILS_FETCH_FAILURE";

// Users list reducer

export const PINNED_USERS_FETCH_REQUEST = "PINNED_USERS_FETCH_REQUEST";
export const PINNED_USERS_FETCH_SUCCESS = "PINNED_USERS_FETCH_SUCCESS";
export const PINNED_USERS_FETCH_FAILURE = "PINNED_USERS_FETCH_FAILURE";

export const SEARCHED_USERS_FETCH_REQUEST = "SEARCHED_USERS_FETCH_REQUEST";
export const SEARCHED_USERS_FETCH_SUCCESS = "SEARCHED_USERS_FETCH_SUCCESS";
export const SEARCHED_USERS_FETCH_FAILURE = "SEARCHED_USERS_FETCH_FAILURE";

