// Theme reducer
export const SWITCH_THEME = "SWITCH_THEME";

// Auth reducer
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const RECOMMENDATIONS_FETCH_REQUEST = "RECOMMENDATIONS_FETCH_REQUEST";
export const RECOMMENDATIONS_FETCH_SUCCESS = "RECOMMENDATIONS_FETCH_SUCCESS";
export const RECOMMENDATIONS_FETCH_FAILURE = "RECOMMENDATIONS_FETCH_FAILURE";